import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAEBD7',
  },
  errorText: {
    color: '#B01E28',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 40,
    paddingHorizontal: 24,
  },
  reconnectButton: {
    marginTop: 24,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#97572B',
    borderRadius: 16,
  },
  reconnectButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  contentContainer: {
    paddingBottom: 100,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 24,
    paddingBottom: 20,
    backgroundColor: '#FAEBD7',
    borderBottomWidth: 1,
    borderBottomColor: '#97572B20',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#000000',
  },
  settingsButton: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#97572B10',
    borderWidth: 1,
    borderColor: '#97572B30',
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 24,
    gap: 32,
  },
  userCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 24,
  },
  avatarContainer: {
    position: 'relative',
  },
  avatarGradient: {
    width: 96,
    height: 96,
    borderRadius: 48,
    padding: 2,
    backgroundColor: '#97572B',
  },
  avatarInner: {
    width: '100%',
    height: '100%',
    borderRadius: 46,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  levelBadge: {
    position: 'absolute',
    bottom: -8,
    right: -8,
    backgroundColor: '#97572B',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  levelText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 12,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 24,
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#97572B70',
    textTransform: 'uppercase',
    marginTop: 4,
  },
  bioTokenContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#97572B20',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 8,
    alignSelf: 'flex-start',
    gap: 6,
  },
  bioTokenText: {
    color: '#97572B',
    fontWeight: 'bold',
    fontSize: 14,
  },
  xpContainer: {
    marginTop: 16,
    width: '100%',
  },
  xpHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  xpLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#97572B70',
    textTransform: 'uppercase',
  },
  xpValue: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#97572B',
  },
  xpBarTrack: {
    height: 8,
    backgroundColor: '#97572B15',
    borderRadius: 4,
    overflow: 'hidden',
  },
  xpBarFill: {
    height: '100%',
    backgroundColor: '#97572B',
    borderRadius: 4,
  },
  badgesContainer: {
    gap: 16,
  },
  badgesScroll: {
    marginHorizontal: -24,
    paddingHorizontal: 24,
  },
  badge: {
    width: 112,
    height: 112,
    borderRadius: 28,
    backgroundColor: '#FAEBD7',
    borderWidth: 1,
    borderColor: '#97572B20',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginRight: 12,
  },
  badgeIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FAEBD7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#97572B80',
    textAlign: 'center',
    lineHeight: 14,
  },
  bioText: {
    backgroundColor: '#FAEBD7',
    borderRadius: 16,
    padding: 16,
    fontSize: 14,
    fontWeight: '500',
    color: '#00000080',
    textAlign: 'center',
  },
  changeDescButton: {
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#97572B',
    alignItems: 'center',
  },
  changeDescButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  capturesContainer: {},
  capturesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  capturesTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
  },
  capturesCount: {
    fontSize: 14,
    fontWeight: '600',
    color: '#97572B60',
  },
  captureCard: {
    backgroundColor: '#FAEBD7',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: '#97572B20',
  },
  captureHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  captureAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  captureText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#00000080',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: '#00000050',
    justifyContent: 'flex-end',
  },
  settingsModal: {
    backgroundColor: '#FAEBD7',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
  },
  settingsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#97572B20',
    backgroundColor: '#FFFFFF40',
  },
  settingsTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsIcon: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#97572B10',
  },
  settingsTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#97572B',
  },
  closeButton: {
    padding: 8,
  },
  settingsContent: {
    paddingBottom: 120,
  },
  settingsSection: {
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: '#97572B50',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  settingsItems: {
    gap: 8,
  },
  settingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#97572B10',
  },
  settingsItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsItemLabel: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  deleteModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    margin: 24,
    maxHeight: 300,
  },
  deleteContent: {
    padding: 24,
    alignItems: 'center',
  },
  deleteIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#B01E2810',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  deleteTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#000000',
    marginBottom: 8,
  },
  deleteText: {
    fontSize: 14,
    color: '#00000060',
    textAlign: 'center',
    marginBottom: 24,
  },
  deleteButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 16,
    backgroundColor: '#FAEBD7',
  },
  cancelText: {
    color: '#97572B',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  confirmButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 16,
    backgroundColor: '#B01E28',
  },
  confirmText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  descriptionModal: {
    backgroundColor: '#FAEBD7',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '80%',
  },
  descriptionModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#97572B20',
    backgroundColor: '#FFFFFF40',
  },
  descriptionModalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#97572B',
  },
  descriptionModalContent: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    gap: 12,
  },
  descriptionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#97572B60',
    textTransform: 'uppercase',
  },
  descriptionInput: {
    minHeight: 100,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    padding: 12,
    fontSize: 14,
    color: '#000000',
    borderWidth: 1,
    borderColor: '#97572B20',
    textAlignVertical: 'top',
  },
  charCount: {
    fontSize: 12,
    color: '#97572B60',
    textAlign: 'right',
  },
  saveButton: {
    marginTop: 12,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#97572B',
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  versionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  versionText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#97572B',
  },
});
