-- ==========================================
-- 🧬 SFR3 - Darwin : Architecture de la BDD
-- ==========================================

-- 1. CRÉATION DES TABLES
-- ------------------------------------------

CREATE TABLE public."CREATURE" (
                                   id uuid DEFAULT gen_random_uuid() NOT NULL,
                                   species_id integer,
                                   player_id uuid,
                                   gamification_name character varying,
                                   scan_url character varying,
                                   scan_quality integer,
                                   gps_location character varying,
                                   scan_date timestamp without time zone DEFAULT now(),
                                   creature_level integer DEFAULT 1,
                                   stat_atq integer,
                                   stat_def integer,
                                   stat_pv integer,
                                   stat_speed integer,
                                   experience integer DEFAULT 0
);

CREATE TABLE public."FIGHT" (
                                id uuid DEFAULT gen_random_uuid() NOT NULL,
                                played_at timestamp without time zone DEFAULT now(),
                                player1_id uuid,
                                player2_id uuid,
                                creature1_id uuid,
                                creature2_id uuid,
                                winner_id uuid,
                                replay_log text
);

CREATE TABLE public."ITEMS" (
                                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
                                name character varying NOT NULL,
                                effect character varying,
                                value integer
);

CREATE TABLE public."INVENTORY" (
                                    player_id uuid NOT NULL,
                                    items_id integer NOT NULL,
                                    quantity integer DEFAULT 1
);

CREATE TABLE public."PLAYER" (
                                 id uuid DEFAULT gen_random_uuid() NOT NULL,
                                 email character varying NOT NULL,
                                 password character varying NOT NULL,
                                 pseudo character varying NOT NULL,
                                 player_level integer DEFAULT 1,
                                 xp integer DEFAULT 1,
                                 bio_token character varying
);

CREATE TABLE public."SPECIES" (
                                  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
                                  name character varying NOT NULL,
                                  description text,
                                  type character varying,
                                  rarity character varying,
                                  base_stat_atq integer,
                                  base_stat_def integer,
                                  base_stat_pv integer,
                                  base_stat_speed integer,
                                  model_3d_url character varying,
                                  average_weigt integer,
                                  average_life_expectancy integer,
                                  latin_name character varying
);

-- 2. CLÉS PRIMAIRES ET CONTRAINTES UNIQUES
-- ------------------------------------------

ALTER TABLE ONLY public."CREATURE" ADD CONSTRAINT "CREATURE_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."FIGHT" ADD CONSTRAINT "FIGHT_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."INVENTORY" ADD CONSTRAINT "INVENTORY_pkey" PRIMARY KEY (player_id, items_id);
ALTER TABLE ONLY public."ITEMS" ADD CONSTRAINT "ITEMS_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."PLAYER" ADD CONSTRAINT "PLAYER_email_key" UNIQUE (email);
ALTER TABLE ONLY public."PLAYER" ADD CONSTRAINT "PLAYER_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."PLAYER" ADD CONSTRAINT "PLAYER_pseudo_key" UNIQUE (pseudo);
ALTER TABLE ONLY public."SPECIES" ADD CONSTRAINT "SPECIES_pkey" PRIMARY KEY (id);

-- 3. CLÉS ÉTRANGÈRES (RELATIONS)
-- ------------------------------------------

ALTER TABLE ONLY public."CREATURE"
    ADD CONSTRAINT "CREATURE_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public."PLAYER"(id) DEFERRABLE,
    ADD CONSTRAINT "CREATURE_species_id_fkey" FOREIGN KEY (species_id) REFERENCES public."SPECIES"(id) DEFERRABLE;

ALTER TABLE ONLY public."FIGHT"
    ADD CONSTRAINT "FIGHT_creature1_id_fkey" FOREIGN KEY (creature1_id) REFERENCES public."CREATURE"(id) DEFERRABLE,
    ADD CONSTRAINT "FIGHT_creature2_id_fkey" FOREIGN KEY (creature2_id) REFERENCES public."CREATURE"(id) DEFERRABLE,
    ADD CONSTRAINT "FIGHT_player1_id_fkey" FOREIGN KEY (player1_id) REFERENCES public."PLAYER"(id) DEFERRABLE,
    ADD CONSTRAINT "FIGHT_player2_id_fkey" FOREIGN KEY (player2_id) REFERENCES public."PLAYER"(id) DEFERRABLE,
    ADD CONSTRAINT "FIGHT_winner_id_fkey" FOREIGN KEY (winner_id) REFERENCES public."PLAYER"(id) DEFERRABLE;

ALTER TABLE ONLY public."INVENTORY"
    ADD CONSTRAINT "INVENTORY_items_id_fkey" FOREIGN KEY (items_id) REFERENCES public."ITEMS"(id) DEFERRABLE,
    ADD CONSTRAINT "INVENTORY_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public."PLAYER"(id) DEFERRABLE;
