-- Données de référence : Dex initial
INSERT INTO public."SPECIES"
(name, description, type, rarity, base_stat_pv, base_stat_atq, base_stat_def, base_stat_speed, model_path, average_weight, average_life_expectancy, latin_name)
VALUES
    ('Alpaca',      NULL, 'Mammifère', 'Rare',      65,  40,  50,  45,  'Alpaca',      70,     20, 'Vicugna pacos'),
    ('Bull',        NULL, 'Mammifère', 'Commun',    90,  100, 75,  55,  'Bull',        600,    20, 'Bos taurus'),
    ('Cow',         NULL, 'Mammifère', 'Commun',    85,  30,  60,  25,  'Cow',         500,    20, 'Bos taurus'),
    ('Deer',        NULL, 'Mammifère', 'Commun',    60,  55,  45,  85,  'Deer',        70,     12, 'Cervidae'),
    ('Dolphin',     NULL, 'Poisson',   'Epic',      70,  60,  50,  95,  'Dolphin',     150,    30, 'Delphinidae'),
    ('Donkey',      NULL, 'Mammifère', 'Commun',    75,  50,  80,  35,  'Donkey',      250,    30, 'Equus africanus asinus'),
    ('Fox',         NULL, 'Mammifère', 'Rare',      45,  65,  40,  80,  'Fox',         7,      5,  'Vulpes vulpes'),
    ('Frog',        NULL, 'Amphibien', 'Commun',    25,  20,  20,  65,  'Frog',        1,      10, 'Anura'),
    ('Goldfish',    NULL, 'Poisson',   'Commun',    20,  15,  25,  50,  'Goldfish',    1,      10, 'Carassius auratus'),
    ('Goose',       NULL, 'Oiseau',    'Commun',    45,  70,  45,  60,  'Goose',       5,      20, 'Anser anser'),
    ('Horse',       NULL, 'Mammifère', 'Commun',    85,  75,  60,  90,  'Horse',       500,    25, 'Equus caballus'),
    ('White Horse', NULL, 'Mammifère', 'Rare',      80,  70,  65,  95,  'Horse_White', 500,    25, 'Equus caballus'),
    ('Husky',       NULL, 'Mammifère', 'Rare',      70,  65,  55,  75,  'Husky',       25,     12, 'Canis lupus familiaris'),
    ('Koi Carp',    NULL, 'Poisson',   'Rare',      35,  25,  40,  50,  'Koi',         3,      25, 'Cyprinus carpio'),
    ('Llama',       NULL, 'Mammifère', 'Commun',    70,  45,  60,  45,  'Llama',       130,    20, 'Lama glama'),
    ('Manta Ray',   NULL, 'Poisson',   'Legendary', 90,  30,  55,  80,  'Manta ray',   1000,   40, 'Manta birostris'),
    ('Pig',         NULL, 'Mammifère', 'Commun',    80,  40,  50,  30,  'Pig',         100,    10, 'Sus scrofa'),
    ('Puffer',      NULL, 'Poisson',   'Commun',    30,  75,  85,  20,  'Puffer',      1,      10, 'Tetraodontidae'),
    ('Pug',         NULL, 'Mammifère', 'Commun',    40,  25,  30,  25,  'Pug',         8,      12, 'Canis lupus familiaris'),
    ('Rat',         NULL, 'Mammifère', 'Commun',    25,  45,  25,  75,  'Rat',         1,      3,  'Rattus norvegicus'),
    ('Shark',       NULL, 'Poisson',   'Epic',      95,  110, 65,  85,  'Shark',       700,    30, 'Selachimorpha'),
    ('Sheep',       NULL, 'Mammifère', 'Commun',    65,  25,  70,  30,  'Sheep',       70,     12, 'Ovis aries'),
    ('Shiba Inu',   NULL, 'Mammifère', 'Rare',      55,  50,  45,  65,  'ShibaInu',    10,     13, 'Canis lupus familiaris'),
    ('Snake',       NULL, 'Reptile',   'Rare',      40,  80,  35,  65,  NULL,          5,      20, 'Serpentes'),
    ('Spider',      NULL, 'Insecte',   'Commun',    20,  75,  25,  60,  'Spider',      1,      2,  'Araneae'),
    ('Wasp',        NULL, 'Insecte',   'Commun',    15,  90,  20,  100, 'Wasp',        1,      1,  'Hymenoptera'),
    ('Whale',       NULL, 'Poisson',   'Legendary', 150, 120, 100, 50,  'Whale',       100000, 70, 'Balaenoptera'),
    ('Wolf',        NULL, 'Mammifère', 'Epic',      70,  85,  55,  80,  'Wolf',        40,     13, 'Canis lupus'),
    ('Worm',        NULL, 'Insecte',   'Commun',    10,  5,   10,  10,  'Worm',        1,      4,  'Lumbricus'),
    ('Zebra',       NULL, 'Mammifère', 'Rare',      75,  60,  50,  85,  'Zebra',       350,    25, 'Equus quagga');
