name: CI_Test_StatusService

on:
  push:
    paths:
      - 'StatusService/**'
  pull_request:
    paths:
      - 'StatusService/**'
  workflow_dispatch:

jobs:
  test_status_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JavaScript environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: StatusService
      - name: Run tests
        run: npm test
        working-directory: StatusService
