name: CI_Test_Python_API

on:
  push:
    paths:
      - 'PythonApi/**'
  pull_request:
    paths:
      - 'PythonApi/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r PythonApi/requirements.txt
      - name: Test Python API with pytest
        run: |
          pytest
      - name: Get test coverage
        run: |
          coverage run -m pytest tests/ --tb=short
          coverage report